ami_coding_pari_na/Search/urls.py
from django.conf.urls import url
from django.urls import path, include
from Search.views import search_view, SearchResutListApi
from django_filters.views import FilterView
app_name = "Search"
urlpatterns = [
    path('search/', search_view, name='search'),
    path('search-list/',SearchResutListApi.as_view(), name='search-list'),
]

ami_coding_pari_na/Usermodule/urls.py
from django.conf.urls import url
from django.urls import path, include

from .views import index, registration_view, login_view, logout_view

app_name = "Usermodule"

urlpatterns = [
    path('', index, name='index'),
    path('register/', registration_view, name='register'),
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
]

ami_coding_pari_na/ami_coding_pari_na/urls.py
from django.contrib import admin
from django.urls import path, include
from Usermodule.views import index

urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/', include('Usermodule.urls')),
    path('', index, name='index'),
    path('search/',include('Search.urls')),
]

ami_coding_pari_na/Search/models.py
from django.db import models
from django.core.validators import validate_comma_separated_integer_list
from Usermodule.models import CustomUser

# Create your models here.

class Search(models.Model):
    user = models.ForeignKey(CustomUser,on_delete=models.CASCADE)
    input_values = models.CharField(validators=[validate_comma_separated_integer_list], max_length=30, blank=True, null=True)
    timestamp = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = "Searches"
    def __str__(self):
        return self.input_values

ami_coding_pari_na/Usermodule/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

class CustomUser(AbstractUser):
    username = models.CharField(
        ('username'),
        max_length=150,
        unique=True,
        help_text=('Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.'),
        error_messages={
            'unique': ("A user with that username already exists."),
        },
    )
    contact_no = models.BigIntegerField(unique=True, default=None, null=True, blank=True)
    REQUIRED_FIELDS=['email',]
    def __str__(self):
        return self.username

ami_coding_pari_na/Search/forms.py
# from django import forms
# from .models import Inputs
# class SearchForm(forms.Forms):
#     input = forms.CharField(required=True, widget=forms.TextInput(attrs={
#         'class':'form-control', 'id':'input_data'
#     }))

#     class Meta:
#         model = Inputs
#         fields = ['input_data',]

ami_coding_pari_na/Usermodule/forms.py
from django import forms
from .models import CustomUser
from django.contrib.auth.models import AbstractUser
from django.contrib.auth.forms import UserCreationForm

class CustomUserCreationForm(UserCreationForm):
    username = forms.CharField(required=True, widget=forms.TextInput(attrs={
        'class':'form-control', 'id':'username'
    }))
    email = forms.EmailField(required=True, widget=forms.TextInput(attrs={
        'class':'form-control', 'id': 'email'
    }))
    contact_no = forms.IntegerField(required=False, widget=forms.TextInput(attrs={
        'class':'form-control', 'id':'contact_no'
    }))
    password1 = forms.CharField(required=False, widget=forms.PasswordInput(
        attrs={'class': 'form-control', 'id': 'password1'}))
    
    password2 = forms.CharField(required=False, widget=forms.PasswordInput(
        attrs={'class': 'form-control', 'id': 'password2'}))

    class Meta:
        model = CustomUser

        fields=['username', 'email', 'contact_no', 'password1', 'password2']

ami_coding_pari_na/Search/views.py
from django.shortcuts import render
from .models import Search
from .serializers import SearchSerializer
from .filters import SearchResultFilter
from django_filters.rest_framework import DjangoFilterBackend
from rest_framework.generics import ListAPIView
from django.contrib.auth.decorators import login_required
# Search Function

@login_required
def search_view(request):
    user_id=request.user.id 
    result = None

    if request.method == 'POST':
        input_values = (request.POST.get('input_values'))
        search_value = int(request.POST.get('search_value'))
        splitted_input_values = input_values.split(',')
        sorted_input_values = []

        for i in splitted_input_values:
            sorted_input_values.append(int(i))
        sorted_input_values.sort(reverse=True)
        search_model = Search.objects.create(input_values=sorted_input_values, user_id=user_id)
        search_model.save()

        if search_value in search_model.input_values:
            result = True
        else:
            result = False

    return render(request,'search/search.html',context={'result':result})

# classBasedView for search result list and API.

class SearchResutListApi(ListAPIView):
    queryset = Search.objects.all()
    serializer_class = SearchSerializer
    filter_backends = [DjangoFilterBackend]
    filterset_class = SearchResultFilter

ami_coding_pari_na/Usermodule/views.py
from django.shortcuts import render, redirect, reverse
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib import messages
from .models import CustomUser
from .forms import CustomUserCreationForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate,login, logout

# Create your views here.

def index(request):
    return render(request,'user/index.html',context={})

def registration_view(request):
    form = CustomUserCreationForm
    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request,'registration successfull')
            return HttpResponseRedirect(reverse('Usermodule:index'))
    else:
        form = CustomUserCreationForm
    return render(request, 'user/registration.html',context={'form':form})

def login_view(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(username=username, password=password)
        if user:
            login(request, user)
            messages.success(request,'Login Successfull')
            return HttpResponseRedirect(reverse('Usermodule:index'))
            
        else:
            messages.warning(request,"Username and Password doesn't match")
    return render(request,'user/login.html')
    
@login_required
def logout_view(request):
    logout(request)
    messages.success(request,'Logout Successfully')
    return redirect('Usermodule:index')

ami_coding_pari_na/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.min.js" integrity="sha384-+YQ4JLhjyBLPDQt//I+STsc9iw4uQqACwlvpslubQzn4u2UU2UFM80nGisd026JF" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-Piv4xVNRyMGpqkS2by6br4gNJ7DXjqk09RmUpJ8jgGtD7zP9yug3goQfGII0yAns" crossorigin="anonymous"></script>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <a class="navbar-brand" href="{% url 'Usermodule:index' %}">KHOJ</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav">
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'Usermodule:index' %}">Home <span class="sr-only">(current)</span></a>
            </li>
            {% if user.is_authenticated %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'Usermodule:logout' %}">Logout</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'Search:search' %}">Search</a>
            </li>
            {% else %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'Usermodule:register' %}">Register</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'Usermodule:login' %}">Login</a>
            </li>
            {% endif %}
          </ul>
        </div>
      </nav>
    <title>{% block title %} Ami coding pari na {% endblock %}</title>
</head>
<body>
    {% block body_block %}
    {% endblock %}
</body>
</html>

ami_coding_pari_na/templates/search/search.html
{% extends 'base.html '%}
{% block title_block %} Search {% endblock %}
{% block body_block %}
<!-- <div class="row">
    <div class="col-12">
        <div class="card ">
            <div class="card-header pdn-sm-x-40">
                <h6>Khoj the search</h6>
            </div>

            <div class="card-body pdn-20 pdn-sm-40 pdn-t-20-imp">
                <div class="pdn-sm-55 pdn-15 bdr">
                    <form method="POST" enctype="multipart/form-data" >
                        {% csrf_token %}
                        <div class="form-group required row">
                            <label for="input_data" class="col-md-2 control-label col-form-label" >Input : </label>
                            <div class="form-group  col-md-4">
                                {{form.input}}
                                <div class="invalid-username-feedback text-danger" style="display: none;"></div>
                            </div>

                            <label for="email" class="col-md-2 col-form-label control-label">Email : </label>
                            <div class="form-group col-md-4">
                                
                                <div class="invalid-name-feedback text-danger" style="display: none;"></div>
                            </div>
                        </div>
                        
                        
                        <div class="form-group row d-flex justify-content-center"  >
                            <button type="submit" class="btn btn-lg btn-success ml-3 my-4 col-md-2 ">
                            Search
                        </button>
                        </div>
                        </div>
                    </form>
                    <div>{{ form.errors }}</div>
                </div>
            </div>
        </div>
    </div> -->
    <div class="container mw-20">
        <div id="app">
            <div class="login-form">
                <div class="card ">
                    <div class="card-body">
                        
                        <h6 class="text-center mb-3">Sign in to your account</h6>
                        <form action="{% url 'Search:search' %}" method="POST" enctype="multipart/form-data" autocomplete="off">
                            {% csrf_token %}
                            <div class="form-group">
                                <input type="text" class="form-control" name="input_values" id="input_values" placeholder="Input Values" >
                            </div>
                            <div class="form-group">
                                <input type="text" class="form-control" name="search_value" id="search_value" placeholder="Search Value" >
                            </div>
                            <div class="form-group my-3 row">
                                <div class="col-12 text-right">
                                    <input type="submit" class="btn btn-primary btn-block" value="Khoj">
                                </div>
                            </div>
                            {% if result != None %}
                            <div class="result">
                                <h2>Result: {{result}}</h2>
                            </div>
                            {% endif %}
                        </form>
                        
                        
                    </div>
                </div>
            </div>
        </div>
    </div>
    {% endblock %}

ami_coding_pari_na/templates/user/index.html
{% extends 'base.html' %}
{% block body_block %}
{% if messages %}
<div class="alert alert-primary alert-dismissible fade show" role="alert">
    {% for message in messages %}
    {{message}}
    {% endfor %}
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
</div>
{% endif %}
<div class="container-fluid pt-3">
    <div class="container-body"></div>
        <h3>Hi! Welcome to the world of KHOJ</h3>
    </div>
</div>
{% endblock %}

ami_coding_pari_na/templates/user/login.html
{% extends 'base.html' %}
{% block title %}User | Login{% endblock %}
{% block body_block %}

<div class="container mw-20">
    <div id="app">
        <div class="login-form">
            <div class="card ">
                <div class="card-body">
                    
                    <h6 class="text-center mb-3">Sign in to your account</h6>
                    <form action="{% url 'Usermodule:login' %}" method="POST" enctype="multipart/form-data" autocomplete="off">
                        {% csrf_token %}
                        <div class="form-group">
                            <input type="text" class="form-control" name="username" id="username" placeholder="Username" >
                        </div>
                        <div class="form-group">
                            <input type="password" class="form-control" name="password" id="password" placeholder="Password" >
                        </div>
                        <div class="row form-group mt-3">
                            <div class="col-6">
                                <div class="custom-control custom-checkbox">
                                    <input type="checkbox" class="custom-control-input" id="customCheck1">
                                    <label class="custom-control-label" for="customCheck1">Remember Me!</label>
                                </div>
                            </div>
                            <div class="col-6 text-right">
                                <a href="#" class="text-forgot"><i class="icon-lock"></i> Forgot password?</a>
                            </div>
                        </div>
                        <div class="form-group my-3 row">
                            <div class="col-12 text-right">
                                <input type="submit" class="btn btn-primary btn-block" value="Submit">
                            </div>
                        </div>
                    </form>
                    
                    <div class="form-group mb-0 mt-2">
                        <div class="col-12 text-center text-muted text-signup">
                            Don't have an account? <a href="{% url 'Usermodule:register' %}" class="text-info">Sign up</a>
                        </div>
                        
                    </div>
                    
                </div>
            </div>
        </div>
    </div>
</div>
    <!-- Placed at the end of the document so the pages load faster -->


    <!--Plugin-->
{% endblock %}

ami_coding_pari_na/templates/user/registration.html
{% extends 'base.html' %}
{% block title %}User | Create User{% endblock %}
{% block body_block %}
<div class="row">
    <div class="col-12">
        <div class="card ">
            <div class="card-header pdn-sm-x-40">
                <h6>Add New User</h6>
            </div>

            <div class="card-body pdn-20 pdn-sm-40 pdn-t-20-imp">
                <div class="pdn-sm-55 pdn-15 bdr">
                    <div>
                        <div class="note"><h6>Note: * Required Field</h6></div>
                    </div>
                    <form method="POST" enctype="multipart/form-data" >
                        {% csrf_token %}
                        <div class="form-group required row">
                            <label for="username" class="col-md-2 control-label col-form-label" >Username : </label>
                            <div class="form-group  col-md-4">
                                {{form.username}}
                                <div class="invalid-username-feedback text-danger" style="display: none;"></div>
                            </div>

                            <label for="email" class="col-md-2 col-form-label control-label">Email : </label>
                            <div class="form-group col-md-4">
                                {{form.email}}
                                <div class="invalid-name-feedback text-danger" style="display: none;"></div>
                            </div>
                        </div>
                        
                        <div class="form-group required row">
                            <label for="contact_no" class="col-md-2 col-form-label control-label">Contact No. : </label>
                            <div class="form-group col-md-4">
                                {{form.contact_no}}
                                <div class="invalid-name-feedback text-danger" style="display: none;"></div>
                            </div>
                        </div>

                        <div class="form-group required row">
                            <label for="password1" class="col-md-2 col-form-label control-label">Password : </label>
                            <div class="form-group col-md-4">
                                {{form.password1}}
                            </div>
                            
                            <label for="password2" class="col-md-2 col-form-label control-label">Confirm Password : </label>
                            <div class="form-group col-md-4">
                                {{form.password2}}
                            </div>   
                        </div>
                        <div class="form-group row d-flex justify-content-center"  >
                            <button type="submit" class="btn btn-lg btn-success ml-3 my-4 col-md-2 ">
                            Register
                        </button>
                        </div>
                        </div>
                    </form>
                    <div>{{ form.errors }}</div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}